### ISSUE TITLE
how can I resolve the dependecies in the example build.sbt

### ISSUE THREAD

**Issue by liam0949** [kensuio-oss/NLP-LSTM-Spark#1]

**Comment by andypetrella** [comment]
probably better trying with the new releases I would say, 0.4.0 or even, I think, 0.5.0

**Comment by liam0949** [comment]
@andypetrella thank you, andy. I'll try the latest version. But, I finally found the coordinate version based on nd4j-native_0.4-rc3.9. Since I am using gradle for spark application building, there were a lot of dependencies conflicts. PS, I am using spark 1.6.1.
